In [5]:
from bs4 import BeautifulSoup
import pandas as pd
import requests

df = pd.DataFrame()
url = 'https://www.basketball-reference.com/leagues/NBA_2022_games.html'

In [6]:
page = requests.get(url)
soup = BeautifulSoup(page.content, 'html.parser')
tbl = soup.find("table")
temp_df = pd.read_html(str(tbl))[0]
temp_df.head()

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,"Tue, Oct 19, 2021",7:30p,Brooklyn Nets,NaN,Milwaukee Bucks,NaN,NaN,NaN,NaN,NaN
1,"Tue, Oct 19, 2021",10:00p,Golden State Warriors,NaN,Los Angeles Lakers,NaN,NaN,NaN,NaN,NaN
2,"Wed, Oct 20, 2021",7:00p,Indiana Pacers,NaN,Charlotte Hornets,NaN,NaN,NaN,NaN,NaN
3,"Wed, Oct 20, 2021",7:00p,Chicago Bulls,NaN,Detroit Pistons,NaN,NaN,NaN,NaN,NaN
4,"Wed, Oct 20, 2021",7:30p,Boston Celtics,NaN,New York Knicks,NaN,NaN,NaN,NaN,NaN

In [15]:
raw_df = pd.read_csv('../Data/raw_data.csv')
raw_df.head()

,Date,H_Team,H_MP,H_FG,H_FGA,H_FG%,H_3P,H_3PA,H_3P%,H_FT,...,A_ORB,A_DRB,A_TRB,A_AST,A_STL,A_BLK,A_TOV,A_PF,A_PTS,A_+/-
0,"July 20, 2021",MIL,240,37,82,0.451,6,27,0.222,25,...,6,31,37,14,11,4,14,21,98,NaN
1,"July 17, 2021",PHO,240,48,87,0.552,13,19,0.684,10,...,11,26,37,26,7,1,11,17,123,NaN
2,"July 14, 2021",MIL,240,39,97,0.402,7,29,0.241,24,...,5,35,40,18,3,9,17,24,103,NaN
3,"July 11, 2021",MIL,240,43,90,0.478,14,36,0.389,20,...,6,30,36,21,3,3,14,24,100,NaN
4,"July 8, 2021",PHO,240,43,88,0.489,20,40,0.500,12,...,18,28,46,21,8,7,9,17,108,NaN

In [14]:
def getShortName(input_name):    
    for short_name, full_name in dict_name.items():
        if input_name == full_name:
            return short_name

dict_name = {}
with open('../Data/full_name.txt', 'r') as f:
    for line in f:
        name = line.split(',') # [short_name, full_name]
        dict_name[name[0]] = name[1].strip()
dict_name

{'GSW': 'Golden State Warriors',
 'OKC': 'Oklahoma City Thunder',
 'SAC': 'Sacramento Kings',
 'HOU': 'Houston Rockets',
 'BOS': 'Boston Celtics',
 'POR': 'Portland Trail Blazers',
 'LAC': 'Los Angeles Clippers',
 'CLE': 'Cleveland Cavaliers',
 'WAS': 'Washington Wizards',
 'SAS': 'San Antonio Spurs',
 'CHO': 'Charlotte Hornets',
 'ATL': 'Atlanta Hawks',
 'TOR': 'Toronto Raptors',
 'NOP': 'New Orleans Pelicans',
 'MIN': 'Minnesota Timberwolves',
 'DAL': 'Dallas Mavericks',
 'IND': 'Indiana Pacers',
 'ORL': 'Orlando Magic',
 'DET': 'Detroit Pistons',
 'DEN': 'Denver Nuggets',
 'CHI': 'Chicago Bulls',
 'PHO': 'Phoenix Suns',
 'MIA': 'Miami Heat',
 'MEM': 'Memphis Grizzlies',
 'MIL': 'Milwaukee Bucks',
 'BRK': 'Brooklyn Nets',
 'NYK': 'New York Knicks',
 'UTA': 'Utah Jazz',
 'PHI': 'Philadelphia 76ers',
 'LAL': 'Los Angeles Lakers'}

In [7]:
data_df = pd.read_csv('../Data/data.csv')
data_df.head()

,Date,H_Team,H_ave3P,H_ave3PA,H_ave2P,H_ave2PA,H_aveFT,H_aveFTA,H_aveORB,H_aveDRB,...,A_aveFTA,A_aveORB,A_aveDRB,A_aveAST,A_aveSTL,A_aveBLK,A_aveTOV,A_avePF,A_Elo,H_Dif
0,"July 20, 2021",MIL,12.0,32.0,30.8,59.0,15.4,22.2,13.6,31.4,...,17.2,7.2,32.2,21.2,6.2,4.0,12.0,20.2,1700.1,7
1,"July 17, 2021",PHO,12.8,31.8,30.6,54.4,14.2,17.2,7.6,34.2,...,23.0,13.8,33.0,23.2,8.4,3.8,10.0,18.8,1704.3,-4
2,"July 14, 2021",MIL,13.0,35.4,29.8,55.6,16.2,22.2,13.2,33.4,...,17.4,8.0,34.0,22.8,6.0,2.2,11.6,19.4,1715.0,6
3,"July 11, 2021",MIL,11.8,36.0,29.0,53.8,15.0,20.8,13.0,32.8,...,18.4,10.2,36.4,21.8,6.2,3.2,11.6,20.0,1720.9,20
4,"July 8, 2021",PHO,10.2,28.6,29.4,59.8,15.8,18.2,10.2,36.4,...,20.4,12.4,34.2,23.8,8.0,4.0,12.2,18.8,1675.0,10

In [13]:
col_name = data_df.columns
col_name

Index(['Date', 'H_Team', 'H_ave3P', 'H_ave3PA', 'H_ave2P', 'H_ave2PA',
       'H_aveFT', 'H_aveFTA', 'H_aveORB', 'H_aveDRB', 'H_aveAST', 'H_aveSTL',
       'H_aveBLK', 'H_aveTOV', 'H_avePF', 'H_Elo', 'A_Team', 'A_ave3P',
       'A_ave3PA', 'A_ave2P', 'A_ave2PA', 'A_aveFT', 'A_aveFTA', 'A_aveORB',
       'A_aveDRB', 'A_aveAST', 'A_aveSTL', 'A_aveBLK', 'A_aveTOV', 'A_avePF',
       'A_Elo', 'H_Dif'],
      dtype='object')

In [17]:
col_name = ['Team','3P','3PA','2P','2PA','FT','FTA','ORB','DRB','AST','STL','BLK','TOV','PF']
lst_H = ['H_'+col for col in col_name]
lst_A = ['A_'+col for col in col_name]

In [18]:
def get_recent(raw_df, team_name, num_recent_games = 5):
    data = []
    index = 0
    while(len(data) < num_recent_games and index < len(df)-1):
        if (team_name == raw_df.iloc[index]['H_Team']):
            data.append(list(raw_df.iloc[index][lst_H]))
        elif (team_name == raw_df.iloc[index]['A_Team']):
            data.append(list(raw_df.iloc[index][lst_A]))
        index += 1

    return pd.DataFrame(data, columns = col_name).agg(['mean']).values.tolist()[0]

get_recent(raw_df, 'BRK')

KeyError: "['H_2P', 'H_2PA'] not in index"

In [ ]:
data = []
num_match_in_a_round = 15
temp = 

for i in range(num_match_in_a_round): 
    row = temp_df.iloc[i]['Date']
    
    H_team = getShortName(temp_df.iloc[i]['Home/Neutral'])
    
    A_team = getShortName(temp_df.iloc[i]['Visitor/Neutral'])

In [ ]:
test_df = pd.DataFrame(data, columns = col_name)

In [8]:
data_df['H_Dif'] = data_df.apply(lambda x: x['H_Dif'] > 0, axis=1)

In [9]:
def remove_object_col(X):
    return X.select_dtypes(exclude=['object'])

In [10]:
# split X và y
y_sr = data_df["H_Dif"] # sr: series
X_df = data_df.drop("H_Dif", axis=1)

---

### Use Logistic Regression to predict

In [ ]:
logistic_regression_model = LogisticRegression(random_state=0)
full_pipeline = make_pipeline(FunctionTransformer(remove_object_col),
                              StandardScaler(), 
                              logistic_regression_model)

full_pipeline.fit(X_df, y_sr)
full_pipeline.predict(test_X_df)

In [ ]:
print()